export const channels = {
  health: 'vetka:health',
  dollsList: 'vetka:dolls:list',
  dollsGet: 'vetka:dolls:get',
  dollsCreate: 'vetka:dolls:create',
  dollsUpdate: 'vetka:dolls:update',
  dollsFavorite: 'vetka:dolls:favorite',
  settingsGetAll: 'vetka:settings:get-all',
  settingsSet: 'vetka:settings:set',
  amazonAddListing: 'vetka:amazon:add-listing',
  amazonRefreshDoll: 'vetka:amazon:refresh-doll',
  amazonReviewCandidate: 'vetka:amazon:review-candidate',
  pricesCurrent: 'vetka:prices:current',
  pricesHistory: 'vetka:prices:history',
  collectorProgress: 'vetka:collector:progress',
} as const;
