export const channels = {
  health: 'vetka:health',
  updatesGetState: 'vetka:updates:get-state',
  updatesCheck: 'vetka:updates:check',
  updatesRestartAndInstall: 'vetka:updates:restart-and-install',
  updatesStateChanged: 'vetka:updates:state-changed',
  dollsList: 'vetka:dolls:list',
  dollsGet: 'vetka:dolls:get',
  dollsCreate: 'vetka:dolls:create',
  dollsUpdate: 'vetka:dolls:update',
  dollsFavorite: 'vetka:dolls:favorite',
  settingsGetAll: 'vetka:settings:get-all',
  settingsSet: 'vetka:settings:set',
  amazonAddListing: 'vetka:amazon:add-listing',
  amazonRefreshDoll: 'vetka:amazon:refresh-doll',
  amazonReviewCandidate: 'vetka:amazon:review-candidate',
  amazonResumeRegion: 'vetka:amazon:resume-region',
  pricesCurrent: 'vetka:prices:current',
  pricesHistory: 'vetka:prices:history',
  collectorProgress: 'vetka:collector:progress',
  ordersList: 'vetka:orders:list',
  ordersGet: 'vetka:orders:get',
  ordersCreate: 'vetka:orders:create',
  ordersTransition: 'vetka:orders:transition',
  ordersTracking: 'vetka:orders:tracking',
} as const;
