import type { CatalogSeedEntry } from './repository';

const rejectTerms = ['used', 'pre-owned', 'lot', 'replacement', 'outfit', 'accessory only'];
const official = 'Mattel official product URL';
type MattelSource = { officialName: string; mattelUrl: string; mattelImageUrl: string };
const source = (officialName: string, mattelUrl: string, mattelImageUrl: string): MattelSource => ({ officialName, mattelUrl, mattelImageUrl });

function entry(
  mattelSku: string, name: string, characterName: string, lineName: string, productType: string,
  monitorStatus: 'active' | 'monitor_only', requiredTerms: string[], sourceUrl: string | null, evidence = official, mattel: MattelSource | null = null,
): CatalogSeedEntry {
  return { mattelSku, name, characterName, lineName, productType, monitorStatus, requiredTerms, rejectTerms,
    searchQuery: `Monster High ${mattelSku}`, sourceUrl, sourceCheckedAt: '2026-07-12', evidence,
    officialName: mattel?.officialName ?? null, mattelUrl: mattel?.mattelUrl ?? null, mattelImageUrl: mattel?.mattelImageUrl ?? null };
}

export const monsterHighSkuCatalog: readonly CatalogSeedEntry[] = [
  entry('JDR63', 'Скелита Калаверас — День мёртвых 2025', 'Скелита Калаверас', 'День мёртвых 2025', 'collector_limited', 'monitor_only', ['Skelita Calaveras', 'Dia de Muertos'], null, official, source('Monster High Skelita Calaveras Collectible Doll, Día De Muertos 2025, Aztec-Inspired Gown', 'https://shop.mattel.com/products/monster-high-skelita-calaveras-da-de-muertos-doll-jdr63', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/f45786e25e63326ea3b046143973b79873920e22_abd6600d-5a2b-4d00-a0ba-5d10d57da21e.jpg?v=1761841282')),
  entry('HYV99', 'Эльвира — Skullector', 'Эльвира', 'Skullector', 'collector_limited', 'monitor_only', ['Elvira'], null, official, source('Monster High Elvira Collector Doll in Black Faux Leather Dress With Silvery Cape And Accessories', 'https://shop.mattel.com/products/monster-high-elvira-collector-doll-hyv99', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/86433b3d74c85042cfafc588fe75f1efe9271df6.jpg?v=1761842170')),
  entry('JDR67', 'Эмили — Skullector x Corpse Bride', 'Эмили', 'Skullector x Corpse Bride', 'collector_limited', 'monitor_only', ['Corpse Bride', 'Emily'], null, official, source('Monster High Skullector Corpse Bride Collectible Doll, Emily in Gothic Wedding Dress With Veil', 'https://shop.mattel.com/products/monster-high-skullector-corpse-bride-doll-jdr67-en-ca', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/551791c6c513794e665305be61084fd19d3594cf_7a34d88c-afaf-4eee-943e-a53815f0e540.jpg?v=1756839785')),
  entry('HNF99', 'Джек Скеллингтон и Салли — Skullector', 'Джек Скеллингтон и Салли', 'Skullector x Disney', 'collector_limited', 'monitor_only', ['Nightmare Before Christmas', 'Jack', 'Sally'], null, 'Supplied registry; official source pending'),
  entry('HGC29', 'Дракулаура — Boo-riginal Creeproduction', 'Дракулаура', 'Boo-riginal Creeproduction', 'reissue_collector', 'active', ['Draculaura', 'Creeproduction'], 'https://shop.mattel.com/collections/monster-high-creeproductions-dolls', 'Supplied registry; official product source pending'),
  entry('HHK55', 'Лагуна Блю — Core', 'Лагуна Блю', 'Core', 'regular', 'monitor_only', ['Lagoona Blue'], 'https://shop.mattel.com/collections/monster-high', 'Supplied registry; current availability to reconfirm'),
  entry('HXJ03', "Уэнсдей Аддамс — Rave'N Dance", 'Уэнсдей Аддамс', 'Monster High x Wednesday', 'partner_collector', 'monitor_only', ['Wednesday', "Rave'N Dance"], 'https://shop.mattel.com/collections/monster-high', official, source('Monster High Wednesday Collectible Doll, Rave’N Wednesday in Black Gown Inspired By Dance Scene', 'https://shop.mattel.com/products/monster-high-raven-wednesday-doll-hxj03', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/ezuygmaeud5mzrgcaks1_3fff500f-3ae2-4689-919b-03a34366a232.jpg?v=1750787159')),
  entry('JDR71', 'Бьянка Барклай — Monster High x Wednesday', 'Бьянка Барклай', 'Monster High x Wednesday', 'partner_collector', 'monitor_only', ['Bianca Barclay', 'Wednesday'], 'https://shop.mattel.com/collections/monster-high', official, source('Monster High X Wednesday Collectible Doll, Bianca Barclay in Nevermore Academy Uniform', 'https://shop.mattel.com/products/monster-high-wednesday-bianca-barclay-doll-jdr71', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/222d01770e5f98a66013dea85edd4eec289d5888.jpg?v=1761841296')),
  entry('HXH76', 'Кэтти Нуар — Core', 'Кэтти Нуар', 'Core', 'regular', 'active', ['Catty Noir'], 'https://shop.mattel.com/products/monster-high-catty-noir-doll-hxh76', official, source('Monster High Catty Noir Fashion Doll With Pet Cat Amulette And Accessories', 'https://shop.mattel.com/products/monster-high-catty-noir-doll-hxh76', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/hudicedndd3giysoreem_b9168004-0713-4534-a9fe-76a440c9e938.png?v=1778259384')),
  entry('HXH80', 'Клодин Вульф — Monster Fest', 'Клодин Вульф', 'Monster Fest', 'regular', 'monitor_only', ['Clawdeen Wolf', 'Monster Fest'], 'https://shop.mattel.com/collections/monster-high', official, source('Monster High Monster Fest Clawdeen Wolf Fashion Doll With Festival Outfit, Band Poster And Accessories', 'https://shop.mattel.com/products/monster-high-monster-fest-clawdeen-wolf-doll-hxh80-en-ca', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/bnyd9hfympyulh0nmka4.png?v=1717618865')),
  entry('HYV64', 'Сюрприз-куклы — Buried Secrets Cozy Creepover', 'Сюрприз-куклы', 'Buried Secrets', 'regular', 'active', ['Buried Secrets', 'Cozy Creepover'], 'https://shop.mattel.com/collections/monster-high', 'Supplied registry; official product source pending'),
  entry('JHK58', 'Венера Макфлайтрап — Boo-riginal Creeproduction', 'Венера Макфлайтрап', 'Boo-riginal Creeproduction', 'reissue_collector', 'active', ['Venus McFlytrap', 'Creeproduction'], 'https://shop.mattel.com/products/monster-high-boo-riginal-creeproduction-venus-mcflytrap-doll-jhk58', official, source('Monster High Boo-Riginal Creeproduction Venus Mcflytrap Doll With Diary, Doll Stand And Pet', 'https://shop.mattel.com/products/monster-high-boo-riginal-creeproduction-venus-mcflytrap-doll-jhk58', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/5dcd6c9d266d0a490e97c893ab4867da4e73983f_c026af70-eb31-46e3-866a-f89f879a25b0.jpg?v=1776430821')),
  entry('JHK59', 'Робекка Стим — Boo-riginal Creeproduction', 'Робекка Стим', 'Boo-riginal Creeproduction', 'reissue_collector', 'active', ['Robecca Steam', 'Creeproduction'], 'https://shop.mattel.com/products/monster-high-boo-riginal-creeproduction-robecca-steam-doll-jhk59', official, source('Monster High Boo-Riginal Creeproduction Robecca Steam Doll With Diary, Doll Stand And Pet', 'https://shop.mattel.com/products/monster-high-boo-riginal-creeproduction-robecca-steam-doll-jhk59', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/18ebfea1cb37270ab11946b758a3ff0cd8fc69af_315e33b5-e2b7-47f7-88b9-b60473da4312.jpg?v=1776430824')),
  entry('JHK57', 'Рошель Гойл — Boo-riginal Creeproduction', 'Рошель Гойл', 'Boo-riginal Creeproduction', 'reissue_collector', 'active', ['Rochelle Goyle', 'Creeproduction'], 'https://shop.mattel.com/products/monster-high-boo-riginal-creeproduction-rochelle-goyle-doll-jhk57', official, source('Monster High Boo-Riginal Creeproduction Rochelle Goyle Doll With Diary, Doll Stand And Pet', 'https://shop.mattel.com/products/monster-high-boo-riginal-creeproduction-rochelle-goyle-doll-jhk57', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/9cdc8c4abed065ec4c19949b42292d60399f5c60.jpg?v=1776430822')),
  entry('HYV90', 'Оперетта — Boo-riginal Creeproduction', 'Оперетта', 'Boo-riginal Creeproduction', 'reissue_collector', 'active', ['Operetta', 'Creeproduction'], 'https://shop.mattel.com/products/monster-high-boo-riginal-creeproduction-operetta-doll-hyv90-en-ca', official, source('Monster High Boo-Riginal Creeproduction Operetta Doll With Diary, Doll Stand And Pet', 'https://shop.mattel.com/products/monster-high-boo-riginal-creeproduction-operetta-doll-hyv90-en-ca', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/0c3425c8fdb3c76b3662bdc034485c7d96e6db42_5e646abc-4df0-4e23-8a9a-043846173fed.jpg?v=1760634984')),
  entry('HYV88', 'Меолодия и Пурсфона — Boo-riginal Creeproduction', 'Меолодия и Пурсфона', 'Boo-riginal Creeproduction', 'reissue_collector', 'active', ['Meowlody', 'Purrsephone', 'Creeproduction'], 'https://shop.mattel.com/products/monster-high-boo-riginal-creeproduction-meowlody-and-purrsephone-dolls-hyv88-en-ca', official, source('Monster High Boo-Riginal Creeproduction Meowlody And Purrsephone Dolls With Diary And Doll Stands', 'https://shop.mattel.com/products/monster-high-boo-riginal-creeproduction-meowlody-and-purrsephone-dolls-hyv88-en-ca', 'https://cdn.shopify.com/s/files/1/0600/0141/9429/files/e7e2509d9cfcef0e8d55dd8456d6a1f4a967fa48_eebff3cf-a1f5-4f26-a396-0d7f5535975f.jpg?v=1760634987')),
  entry('JMB92', 'Виллоу Торн — Moonspell Magic', 'Виллоу Торн', 'Moonspell Magic', 'regular', 'active', ['Willow Thorne', 'Moonspell Magic'], null, 'Supplied registry; official product source pending'),
  entry('JNM26', 'Карина Сонг — Moonspell Magic', 'Карина Сонг', 'Moonspell Magic', 'regular', 'active', ['Carina Song', 'Moonspell Magic'], null, 'Supplied registry; official product source pending'),
  entry('JMB89', 'Клэр де Луна — Moonspell Magic', 'Клэр де Луна', 'Moonspell Magic', 'regular', 'active', ['Claire de Luna', 'Moonspell Magic'], null, 'Supplied registry; official product source pending'),
  entry('JMB91', 'Рей Люмина — Moonspell Magic', 'Рей Люмина', 'Moonspell Magic', 'regular', 'active', ['Rae Lumina', 'Moonspell Magic'], null, 'Supplied registry; official product source pending'),
  entry('JMB90', 'Лейла Стоун — Moonspell Magic', 'Лейла Стоун', 'Moonspell Magic', 'regular', 'active', ['Layla Stone', 'Moonspell Magic'], null, 'Supplied registry; official product source pending'),
];
